## Editable balance numbers for rider physics, rotation, landing strictness, and
## scoring. Example: raise `maximum_pop_impulse` for bigger air off the lip.
class_name RiderTuning
extends Resource

@export var rules_version := "scoring-v1"
@export var fall_line_acceleration := 540.0
@export var slope_gravity := 980.0
@export var uphill_pump_cut_gradient := 0.33
@export var snow_resistance := 48.0
@export var aerodynamic_drag := 0.00115
@export var tuck_drag_multiplier := 0.38
@export var edge_drag := 105.0
@export var brake_drag := 820.0
@export var release_carve_drag := 570.0
@export var steering_response := 480.0
@export var maximum_turn_rate := 3.8
@export var tuck_steering_multiplier := 0.42
@export var brake_turn_multiplier := 1.85
@export var turn_speed_penalty := 460.0
@export var lane_boundary_margin := 90.0
@export var lane_boundary_force := 1250.0
@export var lane_boundary_damping := 6.0
@export var compression_rate := 1.8
@export var maximum_compression := 1.0
@export var compression_window_distance := 220.0
@export var maximum_pop_impulse := 260.0
@export_range(0.0, 1.0) var compression_auto_release_quality := 0.7
@export var flight_arc_height_multiplier := 1.25
@export var maximum_takeoff_course_speed := 500.0
@export var gravity := 980.0
@export var air_drag := 0.05
@export var air_time_scale := 0.72
@export var air_torque := 25.0
@export var maximum_angular_velocity := 12.0
@export var air_angular_damping := 1.2
@export var compact_inertia_multiplier := 0.62
@export var extended_inertia_multiplier := 1.55
@export var landing_prep_damping := 11.0
@export var landing_prep_alignment_assist_degrees := 14.0
@export var grab_rotation_control_multiplier := 0.55
@export var tweak_rotation_control_multiplier := 0.35
@export var grab_reach_duration := 0.12
@export var minimum_grab_duration := 0.2
@export var perfect_angle_degrees := 8.0
@export var clean_angle_degrees := 24.0
@export var crash_angle_degrees := 35.0
@export var perfect_normal_impact := 110.0
@export var crash_normal_impact := 625.0
@export var perfect_angular_velocity := 1.2
@export var crash_angular_velocity := 7.5
@export var minimum_landing_alignment := 0.35
@export var landing_recovery_duration := 0.45
@export var sketchy_recovery_duration := 0.9
@export var runout_drag := 48.0
@export var minimum_runout_speed := 120.0
@export var crash_completion_delay := 1.2
@export var score_approach_speed_cap := 900.0
@export var score_approach_max := 250
@export var score_takeoff_max := 175
@export var score_airtime_cap := 1.5
@export var score_airtime_max := 175
@export var score_rotation_per_rotation := 300
@export var score_grab_duration_cap := 0.8
@export var score_grab_per_second := 150
@export var score_tweak_duration_cap := 0.6
@export var score_tweak_per_second := 100
@export var score_minimum_landing_multiplier := 0.45
